<?php 
define('BASE_DIR','.'.DIRECTORY_SEPARATOR);
define('DATA_DIR',BASE_DIR.'data'.DIRECTORY_SEPARATOR);
define('FOTOS_DIR',BASE_DIR.'fotos'.DIRECTORY_SEPARATOR);
define('BACKUP_DIR',BASE_DIR.'backUpFotos'.DIRECTORY_SEPARATOR);
define('CLASES_DIR',BASE_DIR.'clases'.DIRECTORY_SEPARATOR);
//
